const games = [
  ['Starlight','Arcade','Catch the falling stars before they fade.','nebula','catch'],['Pulse Runner','Arcade','Tap the pulse at just the right moment.','pulse','pulse'],['Golden Hour','Zen','A gentle game of lucky numbers.','gold','number'],['Tide Pool','Zen','Find the calm pair beneath the surface.','mint','memory'],
  ['Orbit','Puzzle','Keep your focus on a moving light.','violet','catch'],['Sunset Loop','Arcade','Time your move with the setting sun.','sunset','pulse'],['Moon Match','Puzzle','Reveal every matching lunar symbol.','nebula','memory'],['Bloom','Zen','Choose a number, take a breath.','mint','number'],
  ['Deep Signal','Arcade','Catch signals from the quiet dark.','pulse','catch'],['Velvet Dice','Puzzle','A slow roll of fortune and fate.','gold','number'],['Lucid','Puzzle','A memory game for late hours.','violet','memory'],['Afterglow','Arcade','Feel the final pulse of the night.','sunset','pulse']
];
const grid=document.querySelector('#gameGrid'), modal=document.querySelector('#gameModal'); let activeGame;
const icons={catch:'✦',pulse:'◉',number:'◌',memory:'☾'};
function render(filter='all'){
 grid.innerHTML=''; games.filter(g=>filter==='all'||g[1]===filter).forEach((g,i)=>{const card=document.createElement('article');card.className='game-card';card.dataset.i=games.indexOf(g);card.innerHTML=`<div class="art ${g[4]} ${g[3]}"><span></span></div><div class="card-top"><span class="card-type">${g[1].toUpperCase()}</span><span class="play-mini">→</span></div><div class="card-bottom"><div><h3>${g[0]}</h3><p>${g[2]}</p></div><span>${icons[g[4]]}</span></div>`;card.onclick=()=>openGame(games.indexOf(g));grid.appendChild(card)})}
function best(name){return localStorage.getItem('nocturne-'+name)||'—'}
function setBest(name,score){let old=+localStorage.getItem('nocturne-'+name)||0;if(score>old){localStorage.setItem('nocturne-'+name,score);return score}return old}
function openGame(i){activeGame=games[i]; const [name,type,desc,,kind]=activeGame;document.querySelector('#gameTitle').textContent=name;document.querySelector('#gameType').textContent=type;document.querySelector('#gameInstructions').textContent=desc;document.querySelector('#bestScore').textContent='Best '+best(name);modal.classList.add('open');modal.setAttribute('aria-hidden','false');start(kind,name)}
function finish(name,score,copy){document.querySelector('#bestScore').textContent='Best '+setBest(name,score);document.querySelector('#gameStage').innerHTML=`<div class="message"><b>${copy}</b>Score: ${score}</div>`;document.querySelector('#gameControls').innerHTML='<button id="again">Play again</button>';document.querySelector('#again').onclick=()=>start(activeGame[4],name)}
function start(kind,name){let stage=document.querySelector('#gameStage'), controls=document.querySelector('#gameControls');controls.innerHTML='';if(kind==='catch'){let score=0,time=12,star;stage.innerHTML='<div class="message"><b>Ready?</b>Catch as many stars as you can.</div>';controls.innerHTML='<button id="start">Start 12 second round</button>';document.querySelector('#start').onclick=()=>{stage.innerHTML=''; let counter=document.createElement('small');counter.style.cssText='position:absolute;align-self:start;margin:18px;color:#aaa;font-family:DM Mono';stage.append(counter);function spawn(){star=document.createElement('button');star.textContent='✦';star.style.cssText=`position:absolute;border:0;background:none;color:#ffce89;font-size:42px;cursor:pointer;left:${10+Math.random()*78}%;top:${10+Math.random()*68}%;filter:drop-shadow(0 0 12px #ffca65)`;star.onclick=()=>{score++;star.remove();spawn()};stage.append(star)}spawn();let t=setInterval(()=>{counter.textContent=`${score} stars · ${time}s`;if(--time<0){clearInterval(t);finish(name,score,'The sky remembers.')}},1000)}}
 else if(kind==='pulse'){let score=0,round=0;stage.innerHTML='<div class="number-display"><strong id="orb">●</strong><small>WAIT FOR THE GLOW</small></div>'; controls.innerHTML='<button id="hit">Tap the pulse</button>';let glow=false,timer; function go(){glow=false;document.querySelector('#orb').style.color='#74727e';timer=setTimeout(()=>{glow=true;document.querySelector('#orb').style.cssText='color:#ff8063;text-shadow:0 0 35px #ff8063';setTimeout(()=>{if(glow){round++;go()}},650)},600+Math.random()*1800)}document.querySelector('#hit').onclick=()=>{if(glow){score+=10;round++;if(round>=5)finish(name,score,'Perfect rhythm.');else go()}else{score=Math.max(0,score-3);document.querySelector('#orb').textContent='×';setTimeout(()=>document.querySelector('#orb').textContent='●',250)}};go()}
 else if(kind==='memory'){let symbols=['✦','☾','●','◆','✦','☾','●','◆'].sort(()=>Math.random()-.5),open=[],matched=0;stage.innerHTML='<div class="memory-grid"></div>';let mg=stage.firstChild;symbols.forEach((s,i)=>{let b=document.createElement('button');b.textContent=s;b.onclick=()=>{if(open.length===2||b.classList.contains('revealed'))return;b.classList.add('revealed');open.push(b);if(open.length===2){setTimeout(()=>{if(open[0].textContent===open[1].textContent){matched+=2;if(matched===8)finish(name,100,'A tranquil mind.')}else open.forEach(x=>x.classList.remove('revealed'));open=[]},500)}};mg.append(b)})}
 else {let target=1+Math.floor(Math.random()*9);stage.innerHTML='<div class="number-display"><strong>?</strong><small>THE NIGHT HAS CHOSEN A NUMBER</small></div>';controls.innerHTML='<div class="choice-row">'+[1,2,3,4,5,6,7,8,9].map(n=>`<button data-n="${n}">${n}</button>`).join('')+'</div>';controls.querySelectorAll('button').forEach(b=>b.onclick=()=>finish(name,b.dataset.n==target?100:Math.abs(b.dataset.n-target)*5, b.dataset.n==target?'The moon agrees.':'A beautiful near miss.'))}}
function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.querySelector('#closeModal').onclick=close;document.querySelector('#modalBackdrop').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.querySelector('#filters').onclick=e=>{if(!e.target.matches('button'))return;document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');render(e.target.dataset.filter)};document.querySelector('#playFeatured').onclick=()=>openGame(0);document.querySelector('#surpriseButton').onclick=()=>openGame(Math.floor(Math.random()*games.length));document.querySelector('#soundButton').onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==='◒'?'◐':'◒';render();
